@startuml
/' users '/
users ||-l-|| total_post_view_counts
users ||-l-|| user_profiles
users ||-u-o{ follows
users ||-u-o{ follows
users ||-d-o{ favorites
users ||-d-o{ comments
users ||-r-o{ posts
users ||-d-{ views_histories
users ||--o{ notifications

/' posts '/
posts ||-d-o{ favorites
posts ||-d-o{ comments
posts ||-d-{ views_histories
posts ||-u-o{ post_tags
posts ||-d-o{ precautions
posts ||-d-o{ baggages
posts ||-d-o{ shopping_lists
posts ||-r-|{ schedules
posts ||--o{ notifications

/' comments '/
comments ||--|| notifications

/' schedules '/
schedules ||-|{ schedule_details
schedules ||--|{ travel_destinations

/' travels_destinations '/
travel_destinations ||-|| m_geographies

/' schedule_detail_images '/
schedule_details ||-|{ schedule_detail_images

/' tags '/
tags ||-lo{ post_tags

/' m_geographies '/
m_geographies ||--|| m_countries
m_geographies ||--|| m_prefectures
m_geographies ||--|| m_cities

@enduml